version: '3'

services:
  server1:
    build: .
    ports:
      - "3000:3000"
  nginx:
    build:
      context: .
      dockerfile: ./reverse-proxy/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    command: ['./wait-for-it.sh', 'server1:3000', '--', 'nginx-debug', '-g', 'daemon off;']