version: "3"

services:
  server1:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - redis
  server2:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - redis
  load_balancer:
    build:
      context: .
      dockerfile: ./reverse-proxy/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    command:
      [
        "./wait-for-it.sh",
        "server1:3000",
        "--",
        "./wait-for-it.sh",
        "server2:3001",
        "--",
        "nginx-debug",
        "-g",
        "daemon off;",
      ]
    depends_on:
      - server1
      - server2
  db_postgresql:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exampledb
    volumes:
      # - ./database/data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
